### ISSUE TITLE
Eav stepping into a method that has a Global variable

### ISSUE THREAD

**Issue by davecamp** [bmx-ng/bmx-ng#165]
**Describe the bug**
```
SuperStrict

Global Foo:TestType = New TestType

Type TestType
	Method Do:String()
		Global T:String

		T = "Test.Do"
		Return T
	EndMethod
EndType

DebugStop
Local Bar:String = Foo.Do()     ' <-- Stepping into the Foo.Do method creates an Eav
DebugStop
```

**To Reproduce**
In a debug build, running the above code creates an eav when stepping into the Foo.Do method

**Expected behavior**
Step into the Foo.Do method without an eav.

**Version information (please complete the following information):**
 - OS: Win11
 - bcc/bmk/maxide Version: bmk 3.54 mt-win32-x86, gcc 120200 (cpu x4), bcc[ng] Release Version 0.138

**Comment by GWRon** [comment]
I gave it a run in "gdb":

```
ronny@RonnyPC ~/Arbeit/Tools/BlitzMaxNG/tmp $ gdb -r untitled1.debug
GNU gdb (Ubuntu 12.1-0ubuntu1~22.04) 12.1
Copyright (C) 2022 Free Software Foundation, Inc.
...
Reading symbols from untitled1.debug...
Expanding full symbols from untitled1.debug...
(gdb) r
Starting program: /home/ronny/Arbeit/Tools/BlitzMaxNG/tmp/untitled1.debug 
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib/x86_64-linux-gnu/libthread_db.so.1".
[New Thread 0x7ffff743a640 (LWP 16076)]
...
[New Thread 0x7ffff2430640 (LWP 16086)]
~>DebugStop:
~>
s
~>Debug:
~>
e
~>Debug:
~>
t
~>StackTrace{
~>@/home/ronny/Arbeit/Tools/BlitzMaxNG/tmp/untitled1.bmx<15,0>
~>Function untitled1
~>Global Foo:TestType=$00007ffff74639c0
~>Local Bar:String=""
~>@/home/ronny/Arbeit/Tools/BlitzMaxNG/tmp/untitled1.bmx<7,0>
~>Function Do
~>Local Self:TestType=$00007ffff74639c0

Thread 1 "untitled1.debug" received signal SIGSEGV, Segmentation fault.
0x000000000062d7f5 in brl_appstub_debugger_mt_stdio_DebugEscapeString (bbt_s=0x0) at /home/ronny/Arbeit/Tools/BlitzMaxNG/mod/brl.mod/appstub.mod/.bmx/debugger_mt.stdio.bmx.debug.linux.x64.c:1134
1134		if((bbt_s->length)>4096){
(gdb) 
```

the backtrace is:
```
(gdb) bt
#0  0x000000000062d7f5 in brl_appstub_debugger_mt_stdio_DebugEscapeString (bbt_s=0x0)
    at /home/ronny/Arbeit/Tools/BlitzMaxNG/mod/brl.mod/appstub.mod/.bmx/debugger_mt.stdio.bmx.debug.linux.x64.c:1134
#1  0x00000000006301dd in brl_appstub_debugger_mt_stdio_DumpScope (bbt_scope=<optimized out>, bbt_inst=0x0)
    at /home/ronny/Arbeit/Tools/BlitzMaxNG/mod/brl.mod/appstub.mod/.bmx/debugger_mt.stdio.bmx.debug.linux.x64.c:1552
#2  0x0000000000630394 in brl_appstub_debugger_mt_stdio_DumpScopeStack ()
    at /home/ronny/Arbeit/Tools/BlitzMaxNG/mod/brl.mod/appstub.mod/.bmx/debugger_mt.stdio.bmx.debug.linux.x64.c:1569
#3  0x0000000000630c95 in brl_appstub_debugger_mt_stdio_UpdateDebug (bbt_msg=<optimized out>)
    at /home/ronny/Arbeit/Tools/BlitzMaxNG/mod/brl.mod/appstub.mod/.bmx/debugger_mt.stdio.bmx.debug.linux.x64.c:1662
#4  0x000000000040a708 in __m_untitled1_TestType_Do (o=<optimized out>) at /home/ronny/Arbeit/Tools/BlitzMaxNG/tmp/untitled1.bmx:31
#5  0x000000000040aae3 in _bb_main () at /home/ronny/Arbeit/Tools/BlitzMaxNG/tmp/untitled1.bmx:15
#6  0x000000000062c11b in __bb_brl_appstub_appstub ()
    at /home/ronny/Arbeit/Tools/BlitzMaxNG/mod/brl.mod/appstub.mod/.bmx/appstub.bmx.debug.linux.x64.c:8
#7  0x000000000040a504 in main (argc=1, argv=0x7fffffffdfe8) at /home/ronny/Arbeit/Tools/BlitzMaxNG/mod/brl.mod/appstub.mod/appstub.linux.c:20
```
